# Compound
[[redirects]]
  from = "/compound/manifest.json"
  to = "/compound/manifest.json"
  status = 200
  headers = { Access-Control-Allow-Origin = "*" }
 
[[redirects]]
  from = "/compound/icon"
  to = "/compound/icon.svg"
  status = 200 
  headers = { Access-Control-Allow-Origin = "*" }
 
# Uniswap
[[redirects]]
  from = "/uniswap/manifest.json"
  to = "/uniswap/manifest.json"
  status = 200
 
[[redirects]]
  from = "/uniswap/icon"
  to = "/uniswap/icon.png"
  status = 200 

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200    